### ISSUE TITLE
Exclude private properties from routing

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#4349]
I often found myself trapped with signs of private roads or paths in New Zealand. I checked OSM and they are marked as private property there. These properties must be excluded from navigation.

**Comment by Misalf-git** [comment]
"access=private" can indicate that a road is just privately owned and as such won't be ministered like a public road but is still not prohibited to be used publicly if no overriding rules apply.
 
However, even though private roads aren't prohibited for public use per se, it may still be a useful addition for the routing options.

**Comment by telluroid** [comment]
> "access=private" can indicate that a road is just privately owned and as such won't be ministered like a public road but is still not prohibited to be used publicly if no overriding rules apply.

No, access=private is not to be used by the general public. ownership=private is what you describe.

https://wiki.openstreetmap.org/wiki/Tag:access%3Dprivate

**Comment by biodranik** [comment]
@simonschaufi does it happen only _at the end_ of your routes, or also somewhere _in the middle_ of a longer route?

As far as I remember, the end of the route is allowed, because you may drive, for example, to your own private house, or to your friend's house.

A great improvement would be to highlight that this route ending is a private road. I see two options: change the route line color to another one (red?), and display an icon (which one? Any ideas?) like we're displaying now for toll roads on the route.

**Comment by simonschaufi** [comment]
I didn't have this scenario too often yet but I also had it once in the middle of a routing where the path was totally closed to the public. I can try to find the spot again.

If the routing would be allowed, then it would be great to have a possibility to exclude private property and suggest a different route.

**Comment by biodranik** [comment]
Let's focus on specific cases:
1. The start and the end of the route are ok (you may start or finish at some private property), considering that we'll let users clearly see it, so they can choose another finish point, if necessary.
2. Routing through some private roads in the middle of the route IS A BUG, that should be fixed. Please find an example, so we can investigate and fix it. But please make sure that the road was marked as a private one at osm.org.

**Comment by simonschaufi** [comment]
The place where I got stuck was right here: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=-43.56818%2C172.63097%3B-43.57065%2C172.62980#map=17/-43.56954/172.62833 as the path next to the house number 10 is private (at least I saw a big sign saying this). On OSM it is marked as "designated".

**Comment by Misalf-git** [comment]
That's what I thought you meant initially (I was still wrong about the access tag, though).
So OM seems to do things the right way?

**Comment by endim8** [comment]
> The place where I got stuck was right here: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=-43.56818%2C172.63097%3B-43.57065%2C172.62980#map=17/-43.56954/172.62833 as the path next to the house number 10 is private (at least I saw a big sign saying this). On OSM it is marked as "designated".

This is an OSM data issue. i've marked the footpath as private now 👍

**Comment by simonschaufi** [comment]
> Please don't exclude private roads for bicycle and pedestrian navigation.

Why do you disagree? It doesn't make any sense

**Comment by biodranik** [comment]
@rtsisyk can you please elaborate?
Private segments should not be excluded at the start and at the end of the route. But they should be excluded in the middle for any router type. Do you agree with that? If no, then why?

**Comment by simonschaufi** [comment]
> In certain suburban areas

Can you show an actual example? That would help very much! In OSM you can actually set each option for cars, bicycle and pedestrians.

**Comment by biodranik** [comment]
> In certain suburban areas all land is grabbed and you will go to nowhere except main highway if private segments are excluded from navigation. Such communities are usually protected by gates, but you can walk and ride a bicycle, but not drive a car.

AFAIK, access=private can be set separately for each transport type, and our router is already using that information. @vng right?

**Comment by vng** [comment]
motorcar/motor_vehicle/bicycle/foot=yes/designated/no/private/permissive/destination

**Comment by zorglubu** [comment]
> Private segments should not be excluded at the start and at the end of the route. But they should be excluded in the middle for any router type. Do you agree with that? If no, then why?

Hello @biodranik, I agree with you that if the start or end point is inside a private property, the private segments should not be excluded at the start and at the end of the route.
However, if the end point is not inside a private property, then the private segments should be excluded at the end of the route.
Here is an example (coming from https://help.openstreetmap.org/questions/86835/directions-route-error), the end point is a bar accessible by foot, but OM bring the cars inside a private property.
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=33.48328%2C-117.72313%3B33.47639%2C-117.72157#map=17/33.48003/-117.72154

![Screenshot_20230303-110416_Organic_Maps](https://user-images.githubusercontent.com/31647352/222696871-93518e8c-9c54-4b4d-9664-cd48b99bc16e.png)

**Comment by biodranik** [comment]
Do you have any ideas on how we can detect if the private segment should be or should not be excluded at the end of the route? How can we reliably detect that the final destination is "a private property" or "is not a private property"?

**Comment by zorglubu** [comment]
The solution is obviously not easy and won't be perfect. But if it is possible, I would suggest to look for the closest highway=* of the final destination point. If this highway is public, then the destination is most likely public and the private segments should be excluded at the end of the route. Otherwise, it shouldn't.

Here is another example, where the behavior of Valhala is correct while Graphhopper and Osrm are missing the point.
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=46.78708%2C-2.07442%3B46.78654%2C-2.07709#map=18/46.78714/-2.07601
If you move a bit the destination to the north, Valhala will drive you through the private streets.

**Comment by biodranik** [comment]
It would be great to test your algorithm on different OSM locations to (1) confirm that it works reliably and (2) make a list of control coordinates for unit-tests.

**Comment by zorglubu** [comment]
I have spent two hours looking for other examples in my country (highways with restrictions near a possible destination). I found things like that (https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.6685%2C2.1291%3B48.6922%2C2.1237#map=15/48.6804/2.1277), but really, I am not sure now that the extent of the problem is worth the effort.

**Comment by thegrasshopper104** [comment]
Here an example where OM routed me through a `motor_vehicle=designated` street which is only accessible for buses or taxis:
https://www.openstreetmap.org/way/25215335

**Comment by mitteneer** [comment]
I do understand if this is not a high priority/an edge case, but fwiw, this was one of my first routes I used OrganicMaps with a while ago and subsequently stopped using it after it routed me onto a driveway, and through a fence:

<img width="270" height="600" alt="Image" src="https://github.com/user-attachments/assets/fc2ed241-879d-4bbf-a43f-75d13779fa09" />

#7202 is probably related in my case as well. There may be some OSM data issues (I've since marked the driveways in that neighborhood with `ownership=private` as per this thread) but [OSRM routes correctly](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=35.95698%2C-83.9292%3B35.9831596%2C-83.9953738#map=14/35.97158/-83.96308), so I suppose I'm not sure if that is the case, or what I could do to benefit OM.

**Comment by vng** [comment]
@mitteneer Well, with the same endpoint, OSRM does the same thing :)
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=35.95698%2C-83.9292%3B35.983033%2C-83.997967

Actually, it is a straightforward logic to find the nearest road. If you put the endpoint closer to the parking lot, Organic will make a good route.

<img width="1748" height="1174" alt="Image" src="https://github.com/user-attachments/assets/742cc2e9-97a3-4eae-9531-6160a14de080" />

**Comment by mitteneer** [comment]
@vng My apologies, I didn't mean to make a disingenuous argument. I guess my issue has more to do with #7202, since, while you are correct that routing to the parking lot is much better, just asking OM to take me to Victor Ashe Park will take me to that endpoint
