### ISSUE TITLE
Downloading thrown away if app gets closed

### ISSUE THREAD

**Issue by jidanni** [organicmaps/organicmaps#521]
Closing the app should not interrupt downloading.

**Comment by jidanni** [comment]
Just like Google Play can continue updating apps even if it gets closed.

**Comment by jidanni** [comment]
They're already as a cancel all button at the bottom of the downloading page, if people really want to cancel.

**Comment by rtsisyk** [comment]
> Closing the app should not interrupt map downloading.

This problem should be solved already. What is your version of Organic Maps?

**Comment by biodranik** [comment]
Please provide more details about your use case. Now maps should be downloaded in the background, assuming you did not block Internet access to Downloading Manager service.

**Comment by jidanni** [comment]
> What is your version of Organic Maps?

I had just got it from Google Play moments earlier.

**Comment by rtsisyk** [comment]
I tested on device - maps downloading works in the background.

**Comment by jidanni** [comment]
Well I hope it still continues to run if one closes the app.

**Comment by AlertSubject** [comment]
Can you still reproduce the issue or can this be closed?

**Comment by biodranik** [comment]
The issue is about continuing downloading when the app was unloaded from memory by a user or by the system.

**Comment by AlertSubject** [comment]
Ah, this makes more sense
Maybe the title should be changed to be more concise

I assumed the user was facing the issue that the download didn't continue upon minimizing the app
A persistent download notification might be a good idea to protect against overly aggressive optimizations

**Comment by rtsisyk** [comment]
This ticket has the same solution as #520.

**Comment by pastk** [comment]
Minimization of the app interrupts downloads unless battery optimization is explicitly turned off (Android 9).

**Comment by pastk** [comment]
A user reported
> I changed from Samsung Galaxy Note9 zu S24 Ultra. On the S24 with Andr 14 the automatic optimization can't be turned off in general.

**Comment by patepelo** [comment]
This seems to be happening to Android 14+ devices even when baterry optimization is not turned on. Should I open a specific issue?
