### ISSUE TITLE
Outdoor map style preview - display issues

### ISSUE THREAD

**Issue by poeticus** [organicmaps/organicmaps#6658]
An initial look at the new Outdoors map style preview shows how it improves the visibilty of various features. However, looking specifically at examples for England it appears not to emphasise the following in all cases:
highway=footway
highway=bridleway (foot / cycle / horse riding access)
highway=cycleway.

The screenshot below shows the Dale Head summmit area in the English Lake District National Park. Standard map style on the left, outdoor map style on the right. All paths converging here have a highway=footway tag. Changing to outdoor map style does not change the appearance of one of the paths.

![DaleHead1](https://github.com/organicmaps/organicmaps/assets/118109677/b0181351-92e3-4cfb-8985-e49583d7fbcf)

The only difference I can see is that the paths where the display has changed have an additional tag not present in the unchanged path (sac_scale=mountain_hiking) - screenshot below.

![DaleHead_2](https://github.com/organicmaps/organicmaps/assets/118109677/dd1bf8b1-2f52-4af6-bc53-5df60e2e2504)

I can see the same issue in other Lake District locations (eg around Great Gable and Helvellyn).

The screenshot below is of a popular area of open moorland in the English North York Moors National Park, displayed with outdoor map style. None of the footpaths in white (highway=footway) nor bridleways in black (highway=bridleway) are emphasised, only one short length of track is. 

![HoleofHorcum](https://github.com/organicmaps/organicmaps/assets/118109677/ae2f910f-66bd-42bc-b39a-92160e901d02)

As mentioned above, ways tagged with highway=cycleway also appear not to be emphasised in the outdoor map style.

**Comment by pastk** [comment]
Thanks a lot for your feedback!

> The screenshot below shows the Dale Head summmit area in the English Lake District National Park. Standard map style on the left, outdoor map style on the right. All paths converging here have a highway=footway tag. Changing to outdoor map style does not change the appearance of one of the paths.
>  
> The only difference I can see is that the paths where the display has changed have an additional tag not present in the unchanged path (sac_scale=mountain_hiking) - screenshot below.
> 

Its a bug in the main/generic style. All footways with a `sac_scale` tag are supposed to look like paths (brown dash). Thanks for spotting!

> 
> The screenshot below is of a popular area of open moorland in the English North York Moors National Park, displayed with outdoor map style. None of the footpaths in white (highway=footway) nor bridleways in black (highway=bridleway) are emphasised, only one short length of track is.

I've increased visibility of bridleways modestly by one zoom level in #6590 
Perhaps it should be increased by 2 zooms at least and made thicker too.

With footways its more tricky. They are mapped in urban areas predominantly and we don't want to pollute them.
However raising their visibility by one zoom level should be alright - actually it was like this in the main style not so long ago.

> 
> As mentioned above, ways tagged with highway=cycleway also appear not to be emphasised in the outdoor map style.

Same here. And similarly it should be OK to raise them to the same level as trails.

**Comment by poeticus** [comment]
I think that these particular issues may be specific to the UK and its official systems of rights of way designation, linked to OSM guidance on how to map these.

Apologies in advance for covering things here you probably already know, also for the length of this post!

In England and Wales the main designations are Public Footpath and Public Bridleway, as detailed here:
https://wiki.openstreetmap.org/wiki/Access_provisions_in_the_United_Kingdom#Public_Rights_of_Way

The OSM wiki describes two methods for tagging these: Classic & Alternative.
https://wiki.openstreetmap.org/wiki/Classic_vs_Alternative_tagging_schemes_in_use_in_the_United_Kingdom

In practice what this means is that many footpaths in the hills are tagged with highway=footway whereas many others are tagged with highway=path. Together with ways tagged with highway=bridleway these all provide a network of paths for walking which may be indistinguishable from each other on the ground and which all need to be seen clearly on a map in order to be able to navigate safely in the hills.

Because of this I think it is important that these all should be displayed with the same prominence and at the same zoom levels. 

To illustrate how widespread this issue is and why I think it is important, here are a few examples, all shown in Outdoors style.

The approach to Scafell Pike (the highest mountain in England) in the Lake District National Park. The white path (footway) from Esk Hause (top right) is one of the main ways to the summit (bottom left). For hill walking it doesn't make sense for this to be less prominent than other paths here, nor for it to disappear when zooming out while others remain.

![ScafellPike](https://github.com/organicmaps/organicmaps/assets/118109677/8a6ab4bb-ce02-43b2-9a77-c58bf9e1e783)

Another couple of examples illustrating the same need for consistency of prominence and zoom visibilty. On the left the Old Man of Coniston, one of the principal mountains in the Lake District National Park. Both the main path along the ridge to the top and most paths up are shown in white (footway). On the right Ingleborough (unlabelled at this zoom level at top left, the 2nd highest peak in the Yorkshire Dales National Park) with most of the routes to the summit mapped with footway & so in white.

![COLLAGE2](https://github.com/organicmaps/organicmaps/assets/118109677/3978ceb0-b8ef-4a4d-8437-d26a12152cfc)

It's important that bridleways are distinguishable on the map to indicate that cycling & horse riding is permitted. However, they are integral to the walking network and these two screenshots illustrate the importance of display consistency between footpaths and bridleways. On the left Buckden Pike (Yorkshire Dales National Park) and on the right Skiddaw (4th highest mountain in England & the Lake District).

![COLLAGE1](https://github.com/organicmaps/organicmaps/assets/118109677/0d546167-6770-4326-8b4e-598953799427)

This last screenshot is of the Camel Trail in Cornwall, England. This is on a disused railway line running along the south of the river and is mapped as a cycleway, although some other access is permitted.  The lower prominence compared with the enhanced tracks is evident.

![Camel](https://github.com/organicmaps/organicmaps/assets/118109677/d6cafa64-d4c2-46b6-9925-f7dc9b0d2ee1)

In summary, my view is that if OM is to provide a map style specifically for 'out-of-the-city outdoor activities' then it should meet the needs of these and not be unduly constrained by what's happening in cities. 

The needs of walking in the hills dictate that all paths are displayed sufficiently clearly and at appropriate scales to readily permit navigation. Surely it's better to change map style according to location / activity needs rather than reduce the value of the outdoor map in the hills (where it's needed) because of potential display issues in the city.

A few other points.

While Public Footpaths and Public Bridleways form the majority of public rights of way in England & Wales, Byways are an additional but rarer designation (2% according to the first link above). I'm not sure at the moment how these appear in OM.

In Scotland & Northern Ireland rights of way designations are different (again see first link above). Again I'm not fully clear at the moment on the differences and any impact.

Access rights in general appear to be an issue. For example, most of the tracks shown on this screenshot of a country estate in Yorkshire have no public access and are tagged with access=private tags, but they are enhanced by the Outdoor map style giving the incorrect impression that they may be used for walking etc.

![Harewood](https://github.com/organicmaps/organicmaps/assets/118109677/7bd031cd-9d74-4fd8-b46d-220dba67cc9a)

Finally, thanks for all your efforts on this. I don't mean any of my comments to sound negative, just wanting OM to be be as good & as useful as possible.

**Comment by pastk** [comment]
BTW, how do you like the bridleways' line style (color, dash pattern)? And its distinction from paths and tracks?

My understanding is that they differ from `highway=path` by prioritizing horse riders, while paths are primarily for walking.
Still, by default bridleways could be used by walkers and cyclists even.
So e.g. from hiker's point of view the difference is very subtle.

My concern is that currently bridleways use a darker (almost black) color compared to paths.
Hence its hard to make paths darker / more contrast as it is now (important for the outdoors style).

So maybe it'd make sense to change bridleways' styling to be either lighter than paths (e.g. Carto uses dark green) or similar, but with a different hue or a slightly different pattern (maybe longer spaces between dashes?).

**Comment by pastk** [comment]
@poeticus thanks a lot for your feedback, you make very good points.

The footway vs path is related to
- https://github.com/organicmaps/organicmaps/issues/1796
- https://github.com/organicmaps/organicmaps/issues/3246

Ideally we'd like to render all hiking trails in the same style, regardless whether they're tagged as a footway or a path.
We do this trick with footways tagged with a `sac_scale=*` already (but its buggy and doesn't work in the main style).
In your examples are there any additional tags to hint us that its some dirt path and not a paved sidewalk for sure?

Re cycleways one of the reasons they're not distinct in the woods:
- https://github.com/organicmaps/organicmaps/issues/5289

So we need to come up with a better color first. Increasing line thickness will help also of course.

Re bridleways maybe it makes more sense to style them in-between cycleways and paths somehow? Maybe same color as cycleways (which?) but dashed.

**Comment by poeticus** [comment]
I suppose I'm heavily influenced by decades of walking with the Ordnance Survey 1:25,000 maps for Great Britain. These show public footpaths and public bridleways both in green, with footpaths in a short dashed line, bridleways in a long dashed line as shown in the legend here
https://www.ordnancesurvey.co.uk/documents/Explorer-Generic-Legend-English-2022-09.pdf

So this feels right to me - if it's a green dash I can walk on it, a long green dash means I can also cycle on it.

From a walker's point of view it doesn't really make any difference which it is - I need to be able consistently to see both on a map to know where I can walk. On the ground there's usually no meaningful difference.

It's not quite right to say that bridleways prioritise horse riders. Walkers have equal rights to use both public footpaths and public bridleways. Horse riders and cyclists, however, are not permitted to use public footpaths.

Rendering all public footpaths / hiking trails the same is a good plan, it's always felt a bit odd that paths that are the same on the ground are shown differently depending on the mapper's choice of tagging scheme.

Of course, the issue of access rights and map display mentioned in my earlier post is important. In broader terms this means that a tag of highway=path or highway=track does not indicate any type of public access is permitted without the examination of other tags which define this. 

On an initial look I can't see any tag consistently used alongside highway=footway that would indicate it's not a city pavement / sidewalk. Some in the hills do indicate the surface (gravel, unpaved etc) but many do not. Quite a lot actually do specify foot=designated / designation=public_footpath (which most city pavements will not be) but it's by no means universal and its use would miss out important paths in the hills.

**Comment by pastk** [comment]
Re `access=*` on paths and tracks (and other features) - OM doesn't support it yet for rendering purposes (they're considered for routing though):
- #1312

**Comment by poeticus** [comment]
Not supporting access=* for rendering is a real shame. I think it significantly impacts the usefulness of the Outdoors map style for outdoor activities in some areas. 

Farm tracks in upland areas are an immediate thought here for walking & cycling, although the issue also affects some other tracks and paths. Most land in England and Wales, at least, does not have open access provision.

When walking or cycling in the countryside I need to be confident that my chosen route has public access. Being challenged by landowners can be an unpleasant experience with potential safety issues, particularly where dogs may be involved.

**Comment by biodranik** [comment]
The routing engine takes access to an account. Did you find some issues there?

**Comment by poeticus** [comment]
I hadn't tried routing as that's not how I would normally plan my walks / bike rides. My preference is to select a route by examining the map, always with the option of diverging from it if I feel like it, again using the map as my guide.

However, I have now tested routing across the Harewood House estate shown in the earlier screenshot and have had mixed results.

My first test between 2 points on bridleways north and south of the house successfully avoided the track tagged with access=private that runs N-S to the east of the house.

The walking route largely followed bridleways, which is fine, but the cycling route strangely diverged from these at one point to take a longer route round.

Narrowing the route down to investigate why I discovered the following instance where ways tagged with access=private are used.

In the screenshot on the left, below, the route generated between two points less than 100m apart is 5.9km. On the right, testing whether the bridge is the issue, the generated route follows two sections of service road tagged with access=private, rather than the longer route.

![Harewood _routes](https://github.com/organicmaps/organicmaps/assets/118109677/296d12fa-e5fe-450f-9f40-a75ada25bfef)

The bridge is here:
https://omaps.app/8tfTcaheJh/Bridge

**Comment by poeticus** [comment]
I've had another look at this routing issue and, seeing similar with public bridleways elsewhere, assume it results from the presence of gates. That gates are used in routing in OM I now see confirmed here https://github.com/organicmaps/organicmaps/issues/5858#issuecomment-1703543599

Gates appear to block cycling access on bridleways in OM even where the path / track / etc either side of the gate are tagged as both highway=bridleway and bicycle=yes, and where no access restrictions appear on the gate.

This would appear to mean that a lot of the public bridleway network in England & Wales may not be used in OM routing for cycling as a great many have gates on them.

Some roads are similarly affected. The following is an example where a 9km direct road route is routed by OM along a 23km route with 162m additional ascent due a gate. Unlike the cycling (and car) route, the proposed walking route appears (correctly) to ignore the gate (at Robinson's Pot) and take the direct route.

![COLLAGE_20231204_144027_1](https://github.com/organicmaps/organicmaps/assets/118109677/56042e61-0bae-492c-82f8-ee220176b121)

**Comment by pastk** [comment]
> Gates appear to block cycling access on bridleways in OM even where the path / track / etc either side of the gate are tagged as both highway=bridleway and bicycle=yes, and where no access restrictions appear on the gate.

FYI @vng

**Comment by vng** [comment]
@poeticus Actually, gates without any access add some penalty. So this penalty is greater that a detour on bike, but less than a detour by foot :) What do you propose here? Ignore gates at all? Only some specific? How can we distinguish them?

**Comment by poeticus** [comment]
Without knowing anything about routing processes all I can offer is some observations based on how it feels to me as a map user.

Where a bridleway (comprising either a single way or a number of joined ways) has gates on it which have no defined access restrictions  (as with the Harewood estate example given above) my personal preference would be to ignore the gates when routing for cycling as all I need to do is open them to pass.

By proposing a walking route that passes through the gates OM acknowledges that they have no identified physical access issues (for example they're not locked or otherwise blocked). If I can open a gate on a bridleway and walk through it I can do the same with my bike.

An alternative solution (if possible / acceptable) may be to add another option into the list shown when tapping the 'define roads to avoid' banner that appears when a route is displayed. 

An 'avoid gates' checkbox would allow the user to choose based on either general personal preference or on a case by case basis, in the road example above whether it's worth adding 14km and 162m of ascent to a 9km section of ride for the sake of opening what turns out to be one gate. Deselecting such an option clearly should apply only to gates have no overriding explicitly defined access restriction.

This could also apply to car routing on roads, and would have the benefit of allowing the needs of drivers who may not be able to get out of their car readily & open a gate to be taken into account, while allowing the option for others who wish it to include gated roads in their route.

**Comment by pastk** [comment]
I think the most of the issues mentioned here (bridleways/footways/cycleways visibility) were fixed in the Jan and partly in the upcoming Feb release. Other issues like routing through the gates are discussed in separate issues.

**Comment by poeticus** [comment]
@pastk I'm able to see the changes now with the February release on F-Droid (and thanks for your constructive approach towards making that happen).

These changes to the outdoor style do make things more consistent and clearer. 

The thing that still doesn't look quite right to me, however, is that footpaths tagged as highway=footway (and with no sac_scale tag) are still shown in white, not brown like all other paths.

The screenshots below of the English Lake District are examples of how much less prominent the paths shown in white still are, particularly at this wider zoom level (although it is good that the outdoor style now shows them at this level).

![LakeDistrict](https://github.com/organicmaps/organicmaps/assets/118109677/a86081ce-8402-4cc8-8f37-0cb7c0eb506c)

On the left, the white path leading NE from Scafell Pike / Broad Crag is one of the most used paths up England's highest mountain. On the right, the white path over Brim Fell and on north to Swirl How then east is the main ridge route of the popular Coniston round. There are many footpaths shown in this area and the white ones tend to fade into the background. The fact that some footpaths are shown in brown and some in white is also rather confusing as there is no difference either on the ground or in their designation.

As indicated earlier these footpaths are tagged in accordance with OSM guidance which shows highway=footway as one of two acceptable methods for tagging a public footpath.

I note your earlier point about the potential impact in urban areas of changing the way 'footways' are displayed, but surely the Outdoor style has been created to improve the map display for use in rural / wild areas. In that context why should its impact in urban areas be an issue where presumably the outdoor style is less likely to be used?

**Comment by pastk** [comment]
> As indicated earlier these footpaths are tagged in accordance with OSM guidance which shows highway=footway as one of two acceptable methods for tagging a public footpath.
> 

https://wiki.openstreetmap.org/wiki/Classic_vs_Alternative_tagging_schemes_in_use_in_the_United_Kingdom
It says that `highway=footway` implies `surface=unpaved` in UK. Do you know if its generally followed? I.e. can we expect that the most of paved (urban) footways have an explicit `surface=*`?

Also I wonder if unpaved trails are commonly mapped as `highway=footway` in UK only or some other countries as well?
(I can't recall any)
Then maybe we can display all `footway`s as brown for such countries only?

**Comment by pastk** [comment]
I think first we'll re-colour the "sure cases"
- https://github.com/organicmaps/organicmaps/issues/1796#issuecomment-2044681572
