### ISSUE TITLE
Unauthorised U-turn

### ISSUE THREAD

**Issue by Kamerijker** [organicmaps/organicmaps#9178]
**Describe the issue*
Routing by car proposes an unauthorised U-turn on a primary road in Halle, Belgium
https://www.openstreetmap.org/

![Schermafbeelding 2024-08-31 om 14 13 42](https://github.com/user-attachments/assets/b22942f6-d386-4ce4-9814-74ee5b02c77b)

**System information:**
 - iPad7,6 (17.6.1)
- Organic Maps 2024.08.15-16
- nl-BE
- nl-BE, en-GB, fr-BE, es-BE

**Comment by RedAuburn** [comment]
route: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.741319%2C4.239185%3B50.738304%2C4.235981#map=17/50.740143/4.236587

**Comment by biodranik** [comment]
Are u-turns prohibited in the osm data?

**Comment by Bugsbane** [comment]
I don't know. What I do know is that routing frequently suggests U turns where it is not safe to do so, ie on large, major roads. Really this shouldn't happen anywhere larger than a residential street.

**Comment by map-per** [comment]
It looks like OM suggests the U-Turn at the connection of two OSM road segments right next to, but not at the intersection.

> Are u-turns prohibited in the osm data?

For some reasons there are `no_u_turn` restrictions in the OSM data. 
Usually, however, `no_u_turn` are only added on intersections and not on free track sections.

**Comment by biodranik** [comment]
@vng is it easy to filter out such u-turns on connected segments?

**Comment by vng** [comment]
Well, we should definitely filter U-turns on single roads (without other connections) even if they are split on several ways.

@Kamerijker I see that you have started adding no-u-turn relations. Well, not a problem here, but it looks like mapping for the app :) We should resolve it in a better way in the code, since there are 3 more same points in this particular intersection.

BTW, Graphhopper has the same bug.

**Comment by Kamerijker** [comment]
@vng yes i did add u-turn relations hoping some routers would pick those up, but found out later that most routers are ignoring these relations and use other algorithms to avoid u-turns, and yes GraphHopper has still the same problem even after my changes. OSRM and Valhalla are doing the right job here.

**Comment by muralito** [comment]
> I don't know. What I do know is that routing frequently suggests U turns where it is not safe to do so, ie on large, major roads. Really this shouldn't happen anywhere larger than a residential street.

The problem is how to determine if it is safe or no to do an U turn. Maybe in an urban area you are right, but E.g. if i am driving on a quiet primary road in a rural area, for some reason i miss the intersection to turn right, the router should instruct me to do an U-turn, and not to continue driving several km until i can go back. At least is what i expect from the router.

**Comment by Kamerijker** [comment]
@vng the new OM version I downloaded from the Apple store today didn’t pickup my no-u-turn relations in OSM, so the U-turn problem persist.

**Comment by Kamerijker** [comment]
@vng the most recent OM update I installed today solved this problem.
Many thanks to the support team!

**Comment by map-per** [comment]
Reopening as adding turn restrictions in the OSM database is not a proper fix. The OM routing should also work without these superfluous turn restrictions.
