### ISSUE TITLE
downloaded maps are included in backups by 3rd party apps

### ISSUE THREAD

**Issue by brainchild0** [organicmaps/organicmaps#948]
Currently, a backup of an installed instance of Organic Maps created by Titanium Backup includes the downloaded maps. 

Generally, Android applications store static, downloaded assets in a separate location from data subject to backup by other apps. This choice streamlines backup and restore operations, at the small of expense of requiring the assets to be downloaded again after a restore operation. Requested is an enhancement that changes the application design accordingly.

**Comment by biodranik** [comment]
On iOS, the backup is implemented properly: downloadable maps are not backed up. There are several ways to do it properly on Android:
1. Store maps in a separate subdirectory and exclude them from the backup.
2. Custom BackupAgent implementation with a proper file filter.

getNoBackupFilesDir() is not a good option, because the core WritableDir() contains other files which should be backed up.

**Comment by brainchild0** [comment]
I'm no expert, but I believe  that the Android partition layout includes  specific external directories  for data such as media assets, for example, one being called `/sdcard/data`, which may be a useful location for map data, offering a cleaner separation from user application data.

**Comment by rtsisyk** [comment]
This issue is fixed already.

**Comment by brainchild0** [comment]
For my installation of Organic Maps, the data part of the backup made by [Neo Backup](https://github.com/NeoApplications/Neo-Backup) consumes more than half a gigabyte (before compression).

I am running version and bulid *2022.04.27-2-FDroid*.

**Comment by biodranik** [comment]
Does Neo Backup respect standard Android app backup settings?

**Comment by brainchild0** [comment]
I have no idea whether it does or not.  I personally don't know what the question means.

I there a test I can run to find out, or any term I might look for in the feature list?

**Comment by brainchild0** [comment]
I am still experiencing the problem that prompted the original report. How may I validate whether the reason is due to a limitation in the backup software, versus an issue in   Organic Maps?
